# Cloud Build configuration for YouTube Transcript App
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/youtube-transcript-app:$BUILD_ID', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/youtube-transcript-app:$BUILD_ID']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'youtube-transcript'
      - '--image'
      - 'gcr.io/$PROJECT_ID/youtube-transcript-app:$BUILD_ID'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '300s'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'YOUTUBE_API_KEY=[REDACTED_FOR_SECURITY],GEMINI_API_KEY=[REDACTED_FOR_SECURITY]'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/youtube-transcript-app:$BUILD_ID'

# Logging configuration (required when using service account)
options:
  logging: CLOUD_LOGGING_ONLY

